import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <Header/>
          <main className="flex-1 px-2 flex justify-center">
            {children}
          </main>
          <footer className="py-5">
            <div className="text-center text-sm">
              Copyright © All rights reserved |{" "}
              <a
                href="#"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
              >
                Haru Portfolio
              </a>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
